### ISSUE TITLE
delete of spatial layer

### ISSUE THREAD

**Issue by riripi** [neo4j-contrib/spatial#102]
Removing the spatial layer is not working.

https://github.com/neo4j/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/IndexProviderTest.java#L152 

With the following instructions the layer is still there:

```
 config = new HashMap<String, String>();
    config.put(LayerNodeIndex.LAT_PROPERTY_KEY, "la");       
    config.put(LayerNodeIndex.LON_PROPERTY_KEY, "lo");
    config.put(SpatialIndexProvider.GEOMETRY_TYPE, LayerNodeIndex.POINT_PARAMETER);    
    layerIndex = new LayerNodeIndex("layerIndex", graph, config);
    layerIndex.delete()
```

Instead with the following raise an error:

```
    SpatialDatabaseService s = new SpatialDatabaseService(graph);      
    Listener l = new Listener() {
        @Override
        public void begin(int i) {               
        }
        @Override
        public void worked(int i) {             
        }
        @Override
        public void done() {              
        }
    };
    s.deleteLayer("layerIndex", l);
```

Here is the error:

Exception in thread "main" org.neo4j.graphdb.NotFoundException: More than one relationship[RTREE_REFERENCE, INCOMING] fo
und for NodeImpl#7208228
 at org.neo4j.kernel.impl.core.NodeImpl.getSingleRelationship(NodeImpl.java:305)
 at org.neo4j.kernel.impl.core.NodeProxy.getSingleRelationship(NodeProxy.java:125)
 at org.neo4j.collections.rtree.RTreeIndex$1.onIndexReference(RTreeIndex.java:163)
 at org.neo4j.collections.rtree.RTreeIndex.visitInTx(RTreeIndex.java:372)
 at org.neo4j.collections.rtree.RTreeIndex.visitInTx(RTreeIndex.java:365)
 at org.neo4j.collections.rtree.RTreeIndex.visitInTx(RTreeIndex.java:365)
 at org.neo4j.collections.rtree.RTreeIndex.removeAll(RTreeIndex.java:157)
 at org.neo4j.gis.spatial.DefaultLayer.delete(DefaultLayer.java:296)
 at org.neo4j.gis.spatial.SpatialDatabaseService.deleteLayer(SpatialDatabaseService.java:300)

It seems this case http://code.paananen.fi/2012/09/21/working-around-a-neo4j-spatial-spring-data-for-neo4j-bug/

**Comment by geosmart** [comment]
I  can delete a  layer(LayerNodeIndex.POINT_PARAMETER ) with no exception in neo4j embeded environment, 
but when i close the jvm and restart my app, the layerInde files  generated  in the data path/index/node/lucene .

I delete like this 
```
	private Map<String, String> getSpatialIndexConfig() {
		Map<String, String> spatialMap = new HashMap<String, String>();
		spatialMap.putAll(SpatialIndexProvider.SIMPLE_POINT_CONFIG);
		spatialMap.put(LayerNodeIndex.LAT_PROPERTY_KEY, "lati");
		spatialMap.put(LayerNodeIndex.LON_PROPERTY_KEY, "long");
		return spatialMap;
	}
	public void clearAddressNodeIndex_spatial() { 
		try (Transaction tx = graphDBService.beginTx()) {
			Index<Node> index = graphDBService.index().forNodes(spatial_indexName, getSpatialIndexConfig());
			index.delete();
			tx.success();
		}
	}
```

**Comment by riripi** [comment]
the workaround that I found was :

**Comment by craigtaverner** [comment]
This issue seems to relate to the old IndexProvider API, which has been removed since 3.0. If there are similar issues with the newer procedure API, please report them as new issues.
