### ISSUE TITLE
Error while building spatial

### ISSUE THREAD

**Issue by rahanar** [neo4j-contrib/spatial#108]
Hello,

I tried to build spatial on Ubuntu 12.04 and I am getting this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (make-assembly) on project neo4j-spatial: Failed to create assembly: Error filtering file '/home/user/Documents/Workspace/graphMap/spatial/target/docs/examples/includes/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc': /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1275549002.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.103912989.filtered (File name too long)

I am not sure why it complains about file name being too long since everybody else since to able run it. Can anybody please assist me? Let me know if you need more info or if I missing something.

Thanks

---- I run it with -X flag and got this:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:41.388s
[INFO] Finished at: Fri Aug 09 23:57:31 EDT 2013
[INFO] Final Memory: 24M/124M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (make-assembly) on project neo4j-spatial: Failed to create assembly: Error filtering file '/home/user/Documents/Workspace/graphMap/spatial/target/docs/examples/includes/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc': /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1901707339.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.1888314942.filtered (File name too long) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (make-assembly) on project neo4j-spatial: Failed to create assembly: Error filtering file '/home/user/Documents/Workspace/graphMap/spatial/target/docs/examples/includes/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc': /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1901707339.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.1888314942.filtered (File name too long)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error filtering file '/home/user/Documents/Workspace/graphMap/spatial/target/docs/examples/includes/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc': /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1901707339.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.1888314942.filtered (File name too long)
    at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:433)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: org.apache.maven.plugin.assembly.format.AssemblyFormattingException: Error filtering file '/home/user/Documents/Workspace/graphMap/spatial/target/docs/examples/includes/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc': /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1901707339.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.1888314942.filtered (File name too long)
    at org.apache.maven.plugin.assembly.format.FileFormatter.doFileFilter(FileFormatter.java:93)
    at org.apache.maven.plugin.assembly.format.FileFormatter.format(FileFormatter.java:65)
    at org.apache.maven.plugin.assembly.format.FileSetFormatter.formatFileSetForAssembly(FileSetFormatter.java:100)
    at org.apache.maven.plugin.assembly.archive.task.AddFileSetsTask.addFileSet(AddFileSetsTask.java:134)
    at org.apache.maven.plugin.assembly.archive.task.AddFileSetsTask.execute(AddFileSetsTask.java:87)
    at org.apache.maven.plugin.assembly.archive.phase.FileSetAssemblyPhase.execute(FileSetAssemblyPhase.java:69)
    at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:190)
    at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:378)
    ... 21 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1901707339.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.1888314942.filtered (File name too long)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:96)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:65)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:58)
    at org.apache.maven.plugin.assembly.format.FileFormatter.doFileFilter(FileFormatter.java:86)
    ... 28 more
Caused by: java.io.FileNotFoundException: /home/user/Documents/Workspace/graphMap/spatial/target/archive-tmp/fileSetFormatter.1901707339.tmp/break-up-all-geometries-into-points-and-make-density-islands-s_break_up_all_geometries_into_points_and_make_density_islands.asciidoc.1888314942.filtered (File name too long)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:2202)
    at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:2170)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:83)
    ... 31 more

**Comment by ehx-v1** [comment]
I don't think it actually complains about the name being too long, I'd rather say it can't file the file and then says the file name is too long to be logged completely

**Comment by ehx-v1** [comment]
Just wanted to clarify: I still think this is an issue, just the error is on a different spot than the OP thought.

**Comment by craigtaverner** [comment]
I've not seen this issue in a while. I wonder if it is specific to building on windows? I'll close the issue for now, but if anyone else sees it please report which OS you are building on.
