### ISSUE TITLE
Neo4J Spatial with Neo4J High Availability

### ISSUE THREAD

**Issue by lordmj** [neo4j-contrib/spatial#199]
Hello.  I have an issue where I have a HA cluster and I have an embedded slave with an empty database trying to join the cluster (with a master server).  

I get the following error:

```
2015-10-19 15:10:27.096+0000 ERROR [org.neo4j]: Exception when stopping org.neo4j.kernel.lifecycle.Lifecycle$Delegate@ae93556 org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.stop()V
java.lang.AbstractMethodError: org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.stop()V
    at org.neo4j.kernel.lifecycle.Lifecycles$1.stop(Lifecycles.java:55)
    at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.stop(Lifecycle.java:75)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
    at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:185)
    at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
    at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
2015-10-19 15:10:27.102+0000 ERROR [org.neo4j]: Lifecycle exception Failed to transition component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@ae93556' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@ae93556' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:559)
    at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:200)
    at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
    at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
Caused by: java.lang.AbstractMethodError: org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.shutdown()V
    at org.neo4j.kernel.lifecycle.Lifecycles$1.shutdown(Lifecycles.java:64)
    at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.shutdown(Lifecycle.java:81)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:555)
    ... 18 more
2015-10-19 15:10:27.103+0000 ERROR [org.neo4j]: Chained lifecycle exception Component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@ae93556' failed to stop. Please see attached cause exception.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@ae93556' failed to stop. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:532)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
    at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:185)
    at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
    at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
    at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
Caused by: java.lang.AbstractMethodError: org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.stop()V
    at org.neo4j.kernel.lifecycle.Lifecycles$1.stop(Lifecycles.java:55)
    at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.stop(Lifecycle.java:75)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
    ... 19 more 
```

Also when starting up another Neo4J server instance that's part of the cluster, I get the same error.  However when I restart the server, the new server does start, but the Spatial indexes apparently are not copied over,

**Comment by craigtaverner** [comment]
What version of Neo4j and the Neo4j Spatial library are you using?

In the meantime I can make a few comments about this:
* Neo4j Spatial is not tested with HA clusters
* The error above seems to be related to the expectation of a method at SpatialIndexImplementation.stop(), which was only recently added in the commit at https://github.com/neo4j-contrib/spatial/commit/d6a8058944c053b267072d7e7c8de3ee0d6be759

Looking at the new commit, I see it will through an UnsupportedOperationException. I suspect that will not work for you either. Probably we need to determine what the correct behavior of the stop() method should be and implement that. In the meantime, you are welcome to try the release @amorgner made for Neo4j 2.2.5. See https://github.com/neo4j-contrib/m2/tree/master/releases/org/neo4j/neo4j-spatial/0.14-neo4j-2.2.5

**Comment by lordmj** [comment]
I'm using Neo4j 2.2.5.

I'm currently using Spatial library 0.14-neo4j-2.2.3  I believe I had the same issue with 0.14-neo4j-2.2.5 but I can try it again.

**Comment by craigtaverner** [comment]
I'd love to see the exception with 0.14-neo4j-2.2.5. I'd expect it to be similar, but different in a key way, with AbstractMethodError replaced by UnsupportedOperationException. If so, then we can try it with a tiny modification to remove that exception.

**Comment by lordmj** [comment]
This is the error I get now with the move to 0.14-neo4j-2.2.5

````
 store does not represent the same database as master. Will remove and fetch a new one from master
2015-10-20 08:25:58.635+0000 ERROR [org.neo4j]: Exception when stopping org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e Not supported yet.
java.lang.UnsupportedOperationException: Not supported yet.
	at org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.stop(SpatialIndexImplementation.java:104)
	at org.neo4j.kernel.lifecycle.Lifecycles$1.stop(Lifecycles.java:55)
	at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.stop(Lifecycle.java:75)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:185)
	at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
	at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
2015-10-20 08:25:58.643+0000 ERROR [org.neo4j]: Lifecycle exception Failed to transition component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:559)
	at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:200)
	at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
	at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.shutdown(SpatialIndexImplementation.java:109)
	at org.neo4j.kernel.lifecycle.Lifecycles$1.shutdown(Lifecycles.java:64)
	at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.shutdown(Lifecycle.java:81)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:555)
	... 18 more
2015-10-20 08:25:58.644+0000 ERROR [org.neo4j]: Chained lifecycle exception Component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' failed to stop. Please see attached cause exception.
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' failed to stop. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:532)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:185)
	at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
	at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.stop(SpatialIndexImplementation.java:104)
	at org.neo4j.kernel.lifecycle.Lifecycles$1.stop(Lifecycles.java:55)
	at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.stop(Lifecycle.java:75)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	... 19 more
2015-10-20 08:25:58.645+0000 ERROR [org.neo4j]: Exception when stopping org.neo4j.kernel.NeoStoreDataSource@50418c8b Failed to transition component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:559)
	at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:200)
	at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:1160)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:137)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.stopServicesAndHandleBranchedStore(SwitchToSlave.java:521)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.checkDataConsistency(SwitchToSlave.java:357)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.executeConsistencyChecks(SwitchToSlave.java:316)
	at org.neo4j.kernel.ha.cluster.SwitchToSlave.switchToSlave(SwitchToSlave.java:219)
	at org.neo4j.kernel.ha.cluster.HighAvailabilityModeSwitcher$2.run(HighAvailabilityModeSwitcher.java:328)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:99)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.shutdown(SpatialIndexImplementation.java:109)
	at org.neo4j.kernel.lifecycle.Lifecycles$1.shutdown(Lifecycles.java:64)
	at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.shutdown(Lifecycle.java:81)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:555)
	... 18 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.lifecycle.Lifecycle$Delegate@2f4ee71e' failed to stop. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:532)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:155)
	at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:185)
	... 17 more
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.stop(SpatialIndexImplementation.java:104)
	at org.neo4j.kernel.lifecycle.Lifecycles$1.stop(Lifecycles.java:55)
	at org.neo4j.kernel.lifecycle.Lifecycle$Delegate.stop(Lifecycle.java:75)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:527)
	... 19 more
````

Though I think I need to rebuild my spatial index since it doesn't look like the existing one is compatible with the update to 0.14-neo4j-2.2.5

**Comment by lordmj** [comment]
Get the same error even when I have a cluster of all empty databases.  My master database  starts up successfully while the slaves always throw the exception.

**Comment by craigtaverner** [comment]
I've made a new release for 2.2.6 with a fix that might fix this for you. Download it at https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.15-neo4j-2.2.6/neo4j-spatial-0.15-neo4j-2.2.6-server-plugin.zip?raw=true

Please let me know if this works, and I'll add a link to the README for others.

**Comment by lordmj** [comment]
Ok I think this worked.  I joined the Neo4J cluster with an empty slave and the Spatial indexes copied over.

**Comment by ehx-v1** [comment]
There was a fix, and that fix obviously worked. Is there a reason why this is open?

**Comment by craigtaverner** [comment]
Just insufficiently thorough housekeeping.

**Comment by kadamvandita** [comment]
Hello
I have an issue with Ne04j version 3.0 ,with consistency-check module.The test cases are failing.Below is the stack output.
I have used maven version 3.0.5 and java-version 1.8.Even tried with maven version 3.3.5,3.3.9,3.2.5,still getting the same error.

org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@fe81bbc' failed to stop. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:119)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:158)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:324)
        at org.neo4j.consistency.checking.GraphStoreFixture.generateInitialData(GraphStoreFixture.java:488)
        at org.neo4j.consistency.checking.GraphStoreFixture.access$1200(GraphStoreFixture.java:90)
        at org.neo4j.consistency.checking.GraphStoreFixture$1.evaluate(GraphStoreFixture.java:504)
        at org.neo4j.test.TargetDirectory$TestDirectory$1.evaluate(TargetDirectory.java:132)
        at org.neo4j.test.ExternalResource$1.evaluate(ExternalResource.java:43)
        at org.neo4j.test.FailureOutput$1.evaluate(FailureOutput.java:60)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)


FullCheckIntegrationTest.shouldReportRelationshipGroupRelationshipNotInUseInconsistencies Â» Lifecycle
  FullCheckIntegrationTest.shouldReportNodeInconsistencies Â» Lifecycle Component...
  FullCheckIntegrationTest.shouldReportBrokenSchemaRecordChain Â» Lifecycle Compo...
  FullCheckIntegrationTest.shouldReportInvalidLabelIdInUniquenessConstraintRule Â» Lifecycle
  FullCheckIntegrationTest.shouldReportInvalidLabelIdInIndexRule Â» Lifecycle Com...
  FullCheckIntegrationTest.shouldManageUnusedRecordsWithWeirdDataIn Â» Lifecycle ...
  FullCheckIntegrationTest.shouldReportRelationshipTypeInconsistencies Â» Lifecycle
  FullCheckIntegrationTest.shouldReportRelationshipOtherNodeInconsistencies Â» Lifecycle
  FullCheckIntegrationTest.shouldReportIfSomeKeysAreMissing Â» Lifecycle Componen...
  FullCheckIntegrationTest.shouldReportChainedRelationshipGroupOwnerInconsistency Â» Lifecycle
  FullCheckIntegrationTest.shouldReportRelationshipLabelNameInconsistencies Â» Lifecycle
  FullCheckIntegrationTest.shouldReportInvalidLabelIdInNodePropertyExistenceConstraintRule Â» Lifecycle
  FullCheckIntegrationTest.shouldReportDuplicatedNodePropertyExistenceConstraintRules Â» Lifecycle
  FullCheckIntegrationTest.shouldCheckConsistencyOfAConsistentStore Â» Lifecycle ...
  FullCheckIntegrationTest.shouldReportNothingForUniquenessAndPropertyExistenceConstraintOnSameLabelAndProperty Â» Lifecycle
  FullCheckIntegrationTest.shouldReportInvalidPropertyKeyIdInUniquenessConstraintRule Â» Lifecycle
  FullCheckIntegrationTest.shouldReportRelationshipGroupRelationshipOfOtherTypeInconsistencies Â» Lifecycle
  FullCheckIntegrationTest.shouldReportPropertyKeyNameInconsistencies Â» Lifecycle
  FullCheckIntegrationTest.shouldReportCyclesInDynamicRecordsWithLabels Â» Lifecycle
  FullCheckIntegrationTest.shouldReportIndexInconsistencies Â» Lifecycle Componen...
  FullCheckIntegrationTest.shouldReportDuplicatedRelationshipPropertyExistenceConstraintRules Â» Lifecycle
  ExecutionOrderIntegrationTest.shouldRunChecksInSingleThreadedPass Â» Lifecycle ...
  RelationshipChainExplorerTest.setupStoreAccess:63->createStoreWithOneHighDegreeNodeAndSeveralDegreeTwoNodes:144 Â» Lifecycle
  RelationshipChainExplorerTest.tearDownStoreAccess:69 NullPointer
  RelationshipChainExplorerTest.setupStoreAccess:63->createStoreWithOneHighDegreeNodeAndSeveralDegreeTwoNodes:144 Â» Lifecycle
  RelationshipChainExplorerTest.tearDownStoreAccess:69 NullPointer
  ConsistencyCheckToolTest.failWhenStoreWasNonCleanlyShutdown:183->createGraphDbAndKillIt:200 Â» TransactionFailure
  ConsistencyCheckServiceIntegrationTest.shouldNotReportDuplicateForHugeLongValues Â» Lifecycle
  ConsistencyCheckServiceIntegrationTest.shouldFailIfTheStoreInNotConsistent Â» Lifecycle
  ConsistencyCheckServiceIntegrationTest.shouldSucceedIfStoreIsConsistent Â» Lifecycle
  ConsistencyCheckServiceIntegrationTest.shouldAllowGraphCheckDisabled Â» Lifecycle


Any help will be helpful :)

**Comment by craigtaverner** [comment]
Your exception seems to have nothing to do with 'Neo4j Spatial' which this project is about. It looks more like an issue with Neo4j itself. I would suggest you ask your question on the neo4j project issues page at https://github.com/neo4j/neo4j/issues. Perhaps explain exactly which version of Neo4j (to the patch level, or github branch/commit) and what command you ran (eg. mvn clean package, or other).
