### ISSUE TITLE
OSM import fails with InvalidRecordException: NodeRecord[34] not in use

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#226]
happened during a normal OSMImporter.importFile(...) call with a BatchInserter on an empty graph database:
```
Exception in thread "main" org.neo4j.kernel.impl.store.InvalidRecordException: NodeRecord[34] not in use
	at org.neo4j.kernel.impl.store.NodeStore.getRecord(NodeStore.java:147)
	at org.neo4j.kernel.impl.store.NodeStore.getRecord(NodeStore.java:138)
	at org.neo4j.kernel.impl.transaction.state.Loaders$1.load(Loaders.java:64)
	at org.neo4j.kernel.impl.transaction.state.Loaders$1.load(Loaders.java:53)
	at org.neo4j.unsafe.batchinsert.DirectRecordAccess.getOrLoad(DirectRecordAccess.java:62)
	at org.neo4j.unsafe.batchinsert.DirectRecordAccess.getOrLoad(DirectRecordAccess.java:39)
	at org.neo4j.kernel.impl.transaction.state.RelationshipCreator.relationshipCreate(RelationshipCreator.java:60)
	at org.neo4j.unsafe.batchinsert.BatchInserterImpl.createRelationship(BatchInserterImpl.java:920)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMBatchWriter.createRelationship(OSMImporter.java:1554)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMBatchWriter.createRelationship(OSMImporter.java:1361)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMWriter.createRelationship(OSMImporter.java:453)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMWriter.createOSMNode(OSMImporter.java:651)
	at org.neo4j.gis.spatial.osm.OSMImporter.importFile(OSMImporter.java:1928)
	at org.neo4j.gis.spatial.osm.OSMImporter.importFile(OSMImporter.java:1779)
	at com.ptvgroup.haeg.neo4j.experiments.utility.FileImporter.importOSM(FileImporter.java:70)
	at com.ptvgroup.haeg.neo4j.experiments.utility.FileImporter.importFile(FileImporter.java:57)
	at com.ptvgroup.haeg.neo4j.spatialproject.teststuff.TestImport.main(TestImport.java:41)
```

**Comment by ehx-v1** [comment]
just found out that already happened in Neo4j but should have been fixed: jexp/batch-import/#65

**Comment by ehx-v1** [comment]
sry it's one-street.osm not map.osm but that shouldn't matter

**Comment by ehx-v1** [comment]
after re-reading the entry at Neo4j I noticed it doesn't apply to batch inserting, I requested something like putting errroneous relationship records at the end of the import, sorry for troubling you, it's most probably none of your business

**Comment by ehx-v1** [comment]
or perhaps YOU could make a queue for data an erroneous relationship would be created from? just a try-catch construct, and in the catch block you put a wrapper for the data in a queue so at the end of the import when all nodes are imported you can try again, so it's only an error if the second node is truly not there (and not just yet to be imported), would this make sense?

**Comment by ehx-v1** [comment]
I have no idea what the OSM data looks like, as I don't get the importer to import the most simple test cases and finding out from the OSM file might get quite hard, so I have no idea how exactly that would look, or even if it's possible at all

**Comment by ehx-v1** [comment]
had this thought because after switching to a normal GraphDatabaseService a quite similar errior appeared:
`C:\Users\haeg\Documents\GitHub\spatial(debug output for the previous FileNotFoundException)
Importing with osm-writer: OSMGraphWriter: DatabaseService[Community [C:\Users\haeg\Documents\Neo4j\default.graphdb]]:txInterval[5000]
Exception in thread "main" java.lang.IllegalArgumentException: Other node is null.
	at org.neo4j.kernel.impl.core.NodeProxy.createRelationshipTo(NodeProxy.java:549)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMGraphWriter.createRelationship(OSMImporter.java:1160)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMGraphWriter.createRelationship(OSMImporter.java:957)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMWriter.createRelationship(OSMImporter.java:453)
	at org.neo4j.gis.spatial.osm.OSMImporter$OSMWriter.createOSMNode(OSMImporter.java:651)
	at org.neo4j.gis.spatial.osm.OSMImporter.importFile(OSMImporter.java:1928)
	at org.neo4j.gis.spatial.osm.OSMImporter.importFile(OSMImporter.java:1765)
	at com.ptvgroup.haeg.neo4j.experiments.utility.FileImporter.importOSMAlt(FileImporter.java:83)
	at com.ptvgroup.haeg.neo4j.experiments.utility.FileImporter.importFile(FileImporter.java:57)
	at com.ptvgroup.haeg.neo4j.spatialproject.teststuff.TestImport.main(TestImport.java:41)`

**Comment by ehx-v1** [comment]
here is a screenshot of my test class:
![testimport_java](https://cloud.githubusercontent.com/assets/16056805/14606500/d51ee872-057d-11e6-877e-850b04956d29.PNG)
screenshots of my FileImporter can be found at #223 (check the comment right below yours for the latest version)

**Comment by ehx-v1** [comment]
just remembered my FileImporter changed as following:
![fileimporter3](https://cloud.githubusercontent.com/assets/16056805/14606824/1fa3ae54-057f-11e6-8b09-c3c112bc3dff.PNG)

**Comment by ehx-v1** [comment]
BatchInserterManager is just an AutoCloseable wrapping a BatchInserter and shutting it down upon close() so it's basically a mediator between BatchInserter and try-with-resource

**Comment by ehx-v1** [comment]
so as I mentioned, a construct for reading in relationships at the end when necessary would help a lot

**Comment by ehx-v1** [comment]
perhaps I could try adding it too, I just have to figure out how the OSMImporter works, then get Eclipse to recognize Spatial as project, however I might get still get done quickly, shall we compete who's first? ;-)

**Comment by ehx-v1** [comment]
ohh, no, it goes up and down and from inner class out and into the next inner class, I'm too afraid of messing things up to touch this ':-D better you do ;-)

**Comment by ehx-v1** [comment]
ok I think I should clarify that I plan to use my self-written library in an experimentary project for the company I'm having a practical semester at, so it does have a bit more weight than just some hobby project

**Comment by ehx-v1** [comment]
everything works cleanly when I outcomment the way tag in the OSM but a map without roads is kind of no map right?

**Comment by ehx-v1** [comment]
not sure whether this is still up to date, if you can help me at #232 I don't need this any more, and probably you CAN help me there, so doesn't matter anymore
