### ISSUE TITLE
spatial doesn't build on ubuntu 16.04

### ISSUE THREAD

**Issue by stvno** [neo4j-contrib/spatial#233]
I'm trying to install neo4j spatial on a completely new ubuntu 16.04 machine. I have installed neo4j per these instructions: http://debian.neo4j.org/ and I am building neo4j spatial from source code using mvn install.

It fails at filtering images/get_max_area.png and I'm quite at a loss this is and how to solve it. Attached the output of mvn install -X:

```
[DEBUG] Filtering: images/get_max_area.png
[DEBUG] properties used {java.vendor=Oracle Corporation, env.IM_CONFIG_PHASE=1, env.LESSOPEN=| /usr/bin/lesspipe %s, sun.java.launcher=SUN_STANDARD, env.QT_IM_MODULE=ibus, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, env.GTK2_MODULES=overlay-scrollbar, os.name=Linux, env.UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1139, sun.boot.class.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes, env.PWD=/home/steven/spatial, sun.desktop=gnome, env.LANG=en_US.UTF-8, java.vm.specification.vendor=Oracle Corporation, java.runtime.version=1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03, env.GTK_IM_MODULE=ibus, env.QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1, env.DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path, env.UPSTART_EVENTS=xsession started, bundle.namespace=org.neo4j.gis, env.XDG_VTNR=7, project.build.sourceEncoding=UTF-8, env.DISPLAY=:0, user.name=steven, env.QT4_IM_MODULE=xim, env._=/usr/bin/mvn, maven.build.version=Apache Maven 3.3.9, env.USER=steven, env.SHELL=/bin/bash, env.DESKTOP_SESSION=ubuntu, env.XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop, env.PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin, env.XDG_CURRENT_DESKTOP=Unity, user.language=en, env.XDG_SESSION_DESKTOP=ubuntu, sun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64, classworlds.conf=/usr/share/maven/bin/m2.conf, env.UPSTART_JOB=unity7, java.version=1.8.0_03-Ubuntu, user.timezone=, env.DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-tBF39nXM0N, sun.arch.data.model=64, env.COMPIZ_CONFIG_PROFILE=ubuntu, java.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed, sun.cpu.isalist=, sun.jnu.encoding=UTF-8, file.encoding.pkg=sun.io, env.SHLVL=1, file.separator=/, java.specification.name=Java Platform API Specification, env.GNOME_DESKTOP_SESSION_ID=this-is-deprecated, java.class.version=52.0, env.GDMSESSION=ubuntu, org.slf4j.simpleLogger.defaultLogLevel=debug, user.country=US, env.GNOME_KEYRING_PID=, java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre, java.vm.info=mixed mode, env.LOGNAME=steven, os.version=4.4.0-21-generic, maven-gpg-plugin.version=1.4, path.separator=:, java.vm.version=25.03-b03, env.UPSTART_INSTANCE=, env.LANGUAGE=en_US, neo4j.version=3.0.0-SNAPSHOT, env.XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0, env.QT_QPA_PLATFORMTHEME=appmenu-qt5, env.SESSIONTYPE=gnome-session, env.XDG_SESSION_TYPE=x11, env.JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64, java.awt.printerjob=sun.print.PSPrinterJob, env.TERM=xterm-256color, sun.io.unicode.encoding=UnicodeLittle, awt.toolkit=sun.awt.X11.XToolkit, env.XMODIFIERS=@im=ibus, env.GDM_LANG=en_US, user.home=/home/steven, maven-compiler-plugin.version=3.1, env.JOB=unity-settings-daemon, env.OLDPWD=/home/steven/spatial, java.specification.vendor=Oracle Corporation, env.VTE_VERSION=4205, env.WINDOWID=62914570, java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib, java.vendor.url=http://java.oracle.com/, skinVersion=2, env.MAVEN_CMD_LINE_ARGS= install -X, env.XDG_SEAT=seat0, java.vm.vendor=Oracle Corporation, maven-resources-plugin.version=2.6, maven.home=/usr/share/maven, java.runtime.name=OpenJDK Runtime Environment, sun.java.command=org.codehaus.plexus.classworlds.launcher.Launcher install -X, java.class.path=/usr/share/maven/boot/plexus-classworlds-2.x.jar, env.XDG_SESSION_ID=c1, maven.version=3.3.9, env.QT_ACCESSIBILITY=1, java.vm.specification.name=Java Virtual Machine Specification, github.global.server=github, java.vm.specification.version=1.8, neo4j.java.version=1.7, sun.cpu.endian=little, sun.os.patch.level=unknown, env.HOME=/home/steven, java.io.tmpdir=/tmp, env.LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, env.XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, maven.multiModuleProjectDirectory=/home/steven/spatial, env.SSH_AUTH_SOCK=/run/user/1000/keyring/ssh, env.CLUTTER_IM_MODULE=xim, spatial.test.osm.version=20100819, os.arch=amd64, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, env.INSTANCE=, java.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext, env.XDG_RUNTIME_DIR=/run/user/1000, user.dir=/home/steven/spatial, env.SESSION=ubuntu, env.XAUTHORITY=/home/steven/.Xauthority, env.MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path, env.GTK_MODULES=gail:atk-bridge:unity-gtk-module, line.separator=
, java.vm.name=OpenJDK 64-Bit Server VM, spatial.test.shp.version=20100819, skinArtifactId=default-skin, env.XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/steven, geotools.version=9.2, file.encoding=UTF-8, env.COMPIZ_BIN_PATH=/usr/bin/, skinGroupId=org.neo4j.maven.skins, env.GPG_AGENT_INFO=/home/steven/.gnupg/S.gpg-agent:0:1, java.specification.version=1.8, env.GNOME_KEYRING_CONTROL=, env.XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg, env.MAVEN_PROJECTBASEDIR=/home/steven/spatial, env.LESSCLOSE=/usr/bin/lesspipe %s %s}
[DEBUG] filtering /home/steven/spatial/target/docs/images/get_max_area.png to /home/steven/spatial/target/archive-tmp/fileSetFormatter.1518056577.tmp/get_max_area.png.160201233.filtered
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:14 min
[INFO] Finished at: 2016-04-22T16:22:01-04:00
[INFO] Final Memory: 46M/292M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project neo4j-spatial: Failed to create assembly: Error filtering file '/home/steven/spatial/target/docs/images/get_max_area.png': Mark invalid -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project neo4j-spatial: Failed to create assembly: Error filtering file '/home/steven/spatial/target/docs/images/get_max_area.png': Mark invalid
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error filtering file '/home/steven/spatial/target/docs/images/get_max_area.png': Mark invalid
    at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:477)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: org.apache.maven.plugin.assembly.format.AssemblyFormattingException: Error filtering file '/home/steven/spatial/target/docs/images/get_max_area.png': Mark invalid
    at org.apache.maven.plugin.assembly.format.FileFormatter.doFileFilter(FileFormatter.java:112)
    at org.apache.maven.plugin.assembly.format.FileFormatter.format(FileFormatter.java:79)
    at org.apache.maven.plugin.assembly.format.FileSetFormatter.formatFileSetForAssembly(FileSetFormatter.java:97)
    at org.apache.maven.plugin.assembly.archive.task.AddFileSetsTask.addFileSet(AddFileSetsTask.java:137)
    at org.apache.maven.plugin.assembly.archive.task.AddFileSetsTask.execute(AddFileSetsTask.java:90)
    at org.apache.maven.plugin.assembly.archive.phase.FileSetAssemblyPhase.execute(FileSetAssemblyPhase.java:60)
    at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
    at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:429)
    ... 22 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Mark invalid
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:129)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:96)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:86)
    at org.apache.maven.plugin.assembly.format.FileFormatter.doFileFilter(FileFormatter.java:106)
    ... 29 more
Caused by: java.io.IOException: Mark invalid
    at java.io.BufferedReader.reset(BufferedReader.java:512)
    at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:416)
    at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:205)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:181)
    at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:168)
    at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1856)
    at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1804)
    at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:114)
    ... 32 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by craigtaverner** [comment]
I wonder if this is a secondary error after something earlier one has failed. I notice that the test code in GeoPipesTest has a method called get_max_area, which calls addImageSnippet(). I suspect this test code will generate the get_max_area.png file for the docs, and possibly something is going wrong with that? Could you confirm that the file /home/steven/spatial/target/docs/images/get_max_area.png actually exists and is a valid PNG?

On my computer the file is 868bytes in size. And the filtered file is slightly larger.

Can you run the GeoPipesTest by itself, and does it work without error?

**Comment by stvno** [comment]
I just pulled the latest neo4j-spatial and updated neo4j to 3.0.0 and it still doesn't build (same error).

To answer your questions:
get_max_area.png exists and is a valid png (transparent png with blue and green rectangle):
-rw-rw-r-- 1 steven steven  874 Apr 26 11:43 get_max_area.png

The filtered file I can't seem to find, target/achive-tmp is empty.

Running the GeoPipesTest by itself works just fine:
`mvn -Dtest=GeoPipesTest test`
```
Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.857 sec - in org.neo4j.gis.spatial.pipes.GeoPipesTest
```
This interestingly also produces two jar files: 
-rw-r--r-- 1 steven steven  350575 Apr 26 11:41 neo4j-spatial-0.16-neo4j-3.0.0.jar
-rw-r--r-- 1 steven steven 8270134 Apr 26 11:41 neo4j-spatial-0.16-neo4j-3.0.0-server-plugin.jar

**Comment by ehx-v1** [comment]
To me it looks like creating the filtered file from the original file fails. Anything that could come from, e.g. hash sum not what expected (because e.g. the file changed but some hash sum database didn't update)?

**Comment by ehx-v1** [comment]
Could there be any hash sum issues, e.g. the hash sum database didn't update after the file changed?

**Comment by tuddman** [comment]
I successfully built neo4j-spatial from source (dec 10th) on fresh ubuntu 16.04.   I then loaded it into `$NEO4J_HOME/plugins` folder on a `3.0.6 CE` neo4j instance and it could not recognize the directory.    Upgrading neo4j to version `3.0.7 CE` seems to have solved the issue.   

I know it doesn't help to say 'it worked for me'  but if others are having issues on ubuntu 16.04 ... try using the latest release(s)

**Comment by Andy2003** [comment]
The build-ability of the project is now checked via [github actions](https://github.com/neo4j-contrib/spatial/actions)
