### ISSUE TITLE
Looks like SDN compatibility is broken on the 2.3 branch with SDN 3.4.x :(

### ISSUE THREAD

**Issue by Infiniverse** [neo4j-contrib/spatial#257]
It looks like spatial indexing has been broken on the 2.3 branch with respect to SDN 3.4.x

With this commit:

    commit 1b6f4dcd2c4300345370d55f723d52510b26afec
    Author: Craig Taverner <craig@amanzi.com>
    Date:   Mon Apr 4 11:49:10 2016 +0200

    Updated to Neo4j 2.3.3

SDN (3.4.0.M1 and earlier) allows spatial indexes to be defined as follows:

        @Indexed(indexType = IndexType.POINT, indexName = "locations")
        String wkt

This allow arbitrary WKT, including polygons and lines, to be spatially indexed.

After this commit:

    commit 148c6232548ddb05d9efbb0d1e7ee864616484bb
    Author: Craig Taverner <craig@amanzi.com>
    Date:   Thu Jun 9 15:42:00 2016 +0200

    Fixed invalid index config issues #71

This no longer works. We now get exceptions of the following form. It seem that the indexes are now expecting a point instead of arbitrary wkt. :(

For reference, SDN is using the following index configuration. Maybe the bug is with them?

    MapUtil.stringMap(
                      IndexManager.PROVIDER, "spatial", "geometry_type" , "point","wkt","wkt")

The exception is:

    Caused by: org.neo4j.graphdb.NotFoundException: NODE[6] has no property with propertyKey="longitude".
    at org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:482) ~[neo4j-kernel-2.3.5.jar:2.3.5,5b24f63]
    at org.neo4j.gis.spatial.encoders.SimplePointEncoder.decodeGeometry(SimplePointEncoder.java:65) ~[neo4j-spatial-0.15-neo4j-2.3.3.jar:na]
    at org.neo4j.gis.spatial.indexprovider.LayerNodeIndex.add(LayerNodeIndex.java:126) ~[neo4j-spatial-0.15-neo4j-2.3.3.jar:na]
    at org.neo4j.gis.spatial.indexprovider.LayerNodeIndex.add(LayerNodeIndex.java:41) ~[neo4j-spatial-0.15-neo4j-2.3.3.jar:na]
    at org.neo4j.gis.spatial.indexprovider.LegacyIndexNodeWrapper.addNode(LegacyIndexNodeWrapper.java:52) ~[neo4j-spatial-0.15-neo4j-2.3.3.jar:na]
    at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeAddToLegacyIndex(StateHandlingStatementOperations.java:1430) ~[neo4j-kernel-2.3.5.jar:2.3.5,5b24f63]
    at org.neo4j.kernel.impl.api.OperationsFacade.nodeAddToLegacyIndex(OperationsFacade.java:1138) ~[neo4j-kernel-2.3.5.jar:2.3.5,5b24f63]
    at org.neo4j.kernel.impl.coreapi.LegacyIndexProxy$Type$1.add(LegacyIndexProxy.java:91) ~[neo4j-kernel-2.3.5.jar:2.3.5,5b24f63]
    at org.neo4j.kernel.impl.coreapi.LegacyIndexProxy.internalAdd(LegacyIndexProxy.java:536) ~[neo4j-kernel-2.3.5.jar:2.3.5,5b24f63]
    at org.neo4j.kernel.impl.coreapi.LegacyIndexProxy.add(LegacyIndexProxy.java:390) ~[neo4j-kernel-2.3.5.jar:2.3.5,5b24f63]
    at org.springframework.data.neo4j.fieldaccess.IndexingPropertyFieldAccessorListenerFactory$IndexingPropertyFieldAccessorListener.valueChanged(IndexingPropertyFieldAccessorListenerFactory.java:88) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.fieldaccess.DefaultEntityState.notifyListeners(DefaultEntityState.java:137) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.fieldaccess.DefaultEntityState.setValue(DefaultEntityState.java:114) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.SourceStateTransmitter.setEntityStateValue(SourceStateTransmitter.java:67) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.SourceStateTransmitter.access$100(SourceStateTransmitter.java:37) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.SourceStateTransmitter$3.doWithPersistentProperty(SourceStateTransmitter.java:105) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.SourceStateTransmitter$3.doWithPersistentProperty(SourceStateTransmitter.java:102) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:309) ~[spring-data-commons-1.11.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.SourceStateTransmitter.copyPropertiesTo(SourceStateTransmitter.java:102) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.Neo4jEntityConverterImpl.write(Neo4jEntityConverterImpl.java:170) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister$CachedConverter.write(Neo4jEntityPersister.java:179) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister.persist(Neo4jEntityPersister.java:247) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister.persist(Neo4jEntityPersister.java:235) ~[spring-data-neo4j-3.4.0.M1.jar:na]
    at org.springframework.data.neo4j.support.Neo4jTemplate.save(Neo4jTemplate.java:365) ~[spring-data-neo4j-3.4.0.M1.jar:na]

**Comment by Infiniverse** [comment]
With reference to the fix that @craigtaverner applied to #71 it definitely the case that it's selecting a point index, before testing for the wkt key in:

    MapUtil.stringMap(IndexManager.PROVIDER, "spatial", "geometry_type" , "point","wkt","wkt")

Why do you think that SDN specifies both geometry type and wkt?

To be honest, when I was looking at this a while back I couldn't find any solid documentation of how the index configuration was supposed to work.

Can I propose testing for WKT first before dropping back to point, for backward compatibility? It's clearly the case that someone explicitly asking for WKT or WKB is wanting that, even if they specific a geometry type, whereas those wanting points are unlikely to specify WKT or WKB.

**Comment by craigtaverner** [comment]
It would seem that the SDN was using a feature of the spatial library that is not well tested, making a point index using a single property WKT field, instead of the two property latitude/longitude fields.

I know that I did not support WKT in Point index configs simply because it seemed ambiguous, allowing non-point geometries to be placed into those nodes and then indexed. It would, however, be relatively simple to make a test change, allowing WKT for point and seeing how well that behaves in SDN? Are you planning to do this? I've no experience with SDN, so while I could make a reasonable change to the config code, I would not be able to test in SDN myself.

**Comment by Infiniverse** [comment]
I've submitted a pull request: https://github.com/neo4j-contrib/spatial/pull/258

**Comment by Infiniverse** [comment]
BTW, we're extensively using WKT for points, lines and polygons from SDN and using spatial in this way.

**Comment by craigtaverner** [comment]
Since we merged your pull request, can we assume this issue is fixed?

**Comment by Infiniverse** [comment]
Yes thanks. Joe
