### ISSUE TITLE
Error when importing shp files using neo4j3.4 and spatial 0.15-neo4j-2.3

### ISSUE THREAD

**Issue by Windancer94** [neo4j-contrib/spatial#340]
I have successfully built neo4j spatial but I get the following error at runtime：

Exception in thread "main" java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, D:\Neo4j\neo4j-community-3.4.0\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:137)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:130)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:107)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:199)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newEmbeddedDatabase(GraphDatabaseFactory.java:75)
	at ImportShp.ImportShp(ImportShp.java:19)
	at ImportShp.main(ImportShp.java:37)

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@79defdc' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.extension.KernelExtensionFactory.newInstance(Lorg/neo4j/kernel/impl/spi/KernelContext;Ljava/lang/Object;)Lorg/neo4j/kernel/lifecycle/Lifecycle;".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 8 more

Caused by: java.lang.AbstractMethodError: org.neo4j.kernel.extension.KernelExtensionFactory.newInstance(Lorg/neo4j/kernel/impl/spi/KernelContext;Ljava/lang/Object;)Lorg/neo4j/kernel/lifecycle/Lifecycle;
	at org.neo4j.kernel.extension.KernelExtensions.newInstance(KernelExtensions.java:78)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:61)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 11 more

**Comment by asy32x** [comment]
because there is no spatial version yet for neo4j 3.4 - thats including my question, when is the update for 3.4 coming ?

**Comment by agrwlakshay** [comment]
It is so sad, I want to use date time format in neo4j 3.4 so bad

**Comment by craigtaverner** [comment]
The version for Neo4j 2.3 cannot be used with Neo4j 3.4. We will build and upload a version for Neo4j 3.4 soon. In the meantime, you can either build it yourself or use Neo4j 3.3. But I strongly recommend against using Neo4j 2.3, as that is not supported at all anymore.

**Comment by craigtaverner** [comment]
A version for Neo4j 3.4.1 has been published at https://github.com/neo4j-contrib/spatial/releases/tag/0.25.5-neo4j-3.4.1
