### ISSUE TITLE
building issue mvn install

### ISSUE THREAD

**Issue by mscsf15m027** [neo4j-contrib/spatial#345]
Hi everyone,

When i clone the repository it works fine. But when i run this command 

`mvn install`

It shows an error.

`Error resolving version for 'org.asciidoctor:asciidoctor-maven-plugin': Plugin requires Maven version 3.0.0`

I replaced the maven version in pom.xml file.

```
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctor-maven-plugin</artifactId>
<version>3.0.0</version>
```
But now this error is occurring. 
```
Error building POM (may not be this project's POM).
Project ID: org.asciidoctor:asciidoctor-maven-plugin
POM Location: /home/rana/.m2/repository/org/asciidoctor/asciidoctor-maven-plugin/3.0.0/asciidoctor-maven-plugin-3.0.0.pom

Reason: Not a v4.0.0 POM. for project org.asciidoctor:asciidoctor-maven-plugin at /home/rana/.m2/repository/org/asciidoctor/asciidoctor-maven-plugin/3.0.0/asciidoctor-maven-plugin-3.0.0.pom
```

Please help me in resolving this problem.

**Comment by michael-simons** [comment]
You'll need to upgrade your Maven version. Type in `mvn --version`, should be at least 3.0.0. You probably have 2.x something. No need to change the pom.

**Comment by sk6108** [comment]
Hi!

I tried to install according to the README and it runs quite a while when using `mvn install` but then it runs into an error:

```[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29:30 min
[INFO] Finished at: 2018-07-20T15:11:36+02:00
[INFO] Final Memory: 49M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project neo4j-spatial: There are test failures.
[ERROR] 
```

with the failures:

```

Results :

Failed tests: 
  ProgressLoggingListenerTest.testProgressLoggingListnerWithAllLogs:38->testProgressLoggingListenerWithSpecifiedWaits:62 
Argument(s) are different! Wanted:
forwardingPrintStream.println(
    "100,00 (10/10) - Completed test"
);
-> at org.neo4j.gis.spatial.ProgressLoggingListenerTest.testProgressLoggingListenerWithSpecifiedWaits(ProgressLoggingListenerTest.java:62)
Actual invocation has different arguments:
forwardingPrintStream.println(
    "10.00 (1/10) - Running test"
);
-> at org.neo4j.gis.spatial.rtree.ProgressLoggingListener.lambda$new$0(ProgressLoggingListener.java:46)

  ProgressLoggingListenerTest.testProgressLoggingListnerWithOnlyStartAndEnd:46->testProgressLoggingListenerWithSpecifiedWaits:62 
Argument(s) are different! Wanted:
forwardingPrintStream.println(
    "100,00 (10/10) - Completed test"
);
-> at org.neo4j.gis.spatial.ProgressLoggingListenerTest.testProgressLoggingListenerWithSpecifiedWaits(ProgressLoggingListenerTest.java:62)
Actual invocation has different arguments:
forwardingPrintStream.println(
    "10.00 (1/10) - Running test"
);
-> at org.neo4j.gis.spatial.rtree.ProgressLoggingListener.lambda$new$0(ProgressLoggingListener.java:46)
```

I have installed: 

```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac" ```

Any ideas?

**Comment by craigtaverner** [comment]
@sk6108 I noticed that there is a `,` as decimal separator in your output. I wonder if the problem is a locale setting, and the tests might be locale specific. It is possible for you to set the locale to US English in the JVM before running the tests and see if that helps? If that fixes it, we should find a way to make the tests less sensitive to locale.
